pdfcrop: exit on negative offset

diff --git a/pdfcrop b/pdfcrop
--- a/pdfcrop
+++ b/pdfcrop
@@ -18,12 +18,22 @@ END {print left, bottom, right, top}'
 BBOX=(`gs -q -dBATCH -dNOPAUSE -sDEVICE=bbox "$IN_FILE" 2>&1 | grep -v HiResBoundingBox | sed 's/.*: *//' | awk "$MINMAX_AWK"`)
 # BBOX=(left bottom right top)
 
+echo "BBOX: $BBOX"
+
 # Compute offset and new size
 OFFSET_X=`expr $BBOX[1] - $PADDING_X`
 OFFSET_Y=`expr $BBOX[2] - $PADDING_Y`
 NEW_WIDTH=`expr "(" $BBOX[3] - $OFFSET_X + $PADDING_X ")" "*" 10`
 NEW_HEIGHT=`expr "(" $BBOX[4] - $OFFSET_Y + $PADDING_Y ")" "*" 10`
 
+echo "Offset: $OFFSET_X $OFFSET_Y"
+echo "New size: $NEW_WIDTH $NEW_HEIGHT"
+
+# Exit if OFFSET_X < 0 or OFFSET_Y < 0.
+if [ $OFFSET_X -lt 0 -o $OFFSET_Y -lt 0 ]; then
+  echo "ERROR: Offset must be positive."
+  exit 1
+fi
 
 # Crop PDF
 gs \
